### ISSUE TITLE
Add proxy authentication

### ISSUE THREAD

**Issue by zjael** [zjael/simple-proxy-agent#21]
Add proxy authentication to both http and socks proxies
And be able to pass the username and password to the agent like:
```js
new ProxyAgent('http://user:password@0.0.0.0:8080')
```

Resources to get started:
[HTTP Auth](https://nodejs.org/api/http.html#http_http_request_url_options_callback)
[SOCKS Auth](https://www.npmjs.com/package/socks#socksclientoptions)

**Comment by jufab** [comment]
Ready to review

**Comment by zjael** [comment]
Awesome looks good, yeah i have to rework or add proxy authentication functionality to existing http-proxy.js, and socks-proxy.js in tests.
If you are interested in that part too let me know, otherwise i will merge this as soon as possible, i have the tests working properly.

**Comment by jufab** [comment]
I can try to do something ;)

**Comment by jufab** [comment]
Or, maybe, you can merge this one and open an other one assigne to me with the http and socks proxy 👍

**Comment by jufab** [comment]
it's done

**Comment by zjael** [comment]
Great work! It seems authentication for http-proxy works even with wrong username or password though.
Did some minor changes, gonna look into the issue.

**Comment by jufab** [comment]
It's better now with a bad credential.

**Comment by zjael** [comment]
Nice work, was a pleasure 😊
